# Generated by Django 6.0.2 on 2026-03-02 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_codes', models.JSONField()),
                ('start_timestamp', models.DateTimeField()),
                ('end_timestamp', models.DateTimeField()),
                ('require_compliant_device', models.BooleanField(default=False)),
                ('mfa_method_required', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AccessExceptionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(max_length=50, unique=True)),
                ('user_principal_name', models.EmailField(max_length=254)),
                ('exception_type', models.CharField(max_length=100)),
                ('policy_category', models.CharField(choices=[('Geofence', 'Geofence'), ('Device_Compliance', 'Device Compliance'), ('MFA_Override', 'MFA Override'), ('Other', 'Other')], max_length=50)),
                ('approval_id', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Expired', 'Expired')], default='Pending', max_length=20)),
                ('reason', models.TextField(blank=True, null=True)),
                ('reviewer_upn', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parameters', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='request', to='core.accessparameters')),
            ],
        ),
        migrations.CreateModel(
            name='AccessRequestAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_by', models.EmailField(max_length=254)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('field_name', models.CharField(max_length=100)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='core.accessexceptionrequest')),
            ],
        ),
    ]
