# Generated by Django 6.0.2 on 2026-03-02 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessexceptionrequest',
            name='request_id',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
