# Generated by Django 6.0.2 on 2026-03-02 03:46

import django.core.validators
from django.db import migrations, models


def forwards_copy_country_codes(apps, schema_editor):
    AccessParameters = apps.get_model("core", "AccessParameters")
    for obj in AccessParameters.objects.all().iterator():
        # Old field `country_codes` was a JSONField, typically like ['US'].
        raw = getattr(obj, "country_codes", None)
        code = None
        if isinstance(raw, str):
            code = raw
        elif isinstance(raw, (list, tuple)) and raw:
            code = raw[0]

        if isinstance(code, str):
            code = code.strip().upper()
            if len(code) == 2 and code.isalpha():
                obj.country_code = code
        obj.save(update_fields=["country_code"])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_accessexceptionrequest_request_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessparameters',
            name='country_code',
            field=models.CharField(blank=True, help_text='2-letter ISO country code (e.g. US, GB)', max_length=2, null=True, validators=[django.core.validators.RegexValidator('^[A-Z]{2}$', 'Use a 2-letter uppercase country code (e.g. US, GB).')]),
        ),
        migrations.RunPython(forwards_copy_country_codes, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='accessparameters',
            name='country_codes',
        ),
    ]
