# Generated by Django 6.0.2 on 2026-03-02 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_accessparameters_country_codes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessexceptionrequest',
            name='approval_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='accessexceptionrequest',
            name='policy_category',
            field=models.CharField(choices=[('Geofence', 'Geofence'), ('Device_Compliance', 'Device Compliance'), ('MFA_Override', 'MFA Override'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
