# Generated by Django 6.0.2 on 2026-03-02 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_accessexceptionrequest_approval_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessexceptionrequest',
            name='exception_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
