# Generated by Django 6.0.2 on 2026-03-02 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_accessexceptionrequest_exception_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessexceptionrequest',
            name='exception_type',
        ),
    ]
